public enum ServerPackages
{
    SMsg = 1,
    SLogin,
    SSendToBattle,
    SGiveProbability,
    SGetChoice,
    SSendChoice,
    SEndgame,
    SLeaderboard,
    SDisconnect,
    SGiveAbilities,
    SGiveStats,
    SEmotes,
    SGiveList,
    SFriendly,
    SSpectate,
    SLP,
    SChest,
    SReplay,
    SReconnect,
    SProfile,
}
public enum ClientPackages
{
    CLogin = 1,
    CNewAccount,
    CBattleOnline,
    CGetProbability,
    CGetOtherPlayerChoice,
    CSendChoice,
    CEndGame,
    CDebug,
    CLeaderboard,
    CGetAbilities,
    CMainMenu,
    CGetStats,
    CEmotes,
    CAddFriend,
    CFriendsList,
    CCheckFriend,
    CSpectate,
    CLifePoints,
    CChest,
    CChestOpening,
    CReconnect,
    CAdReward,
}