// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudString s_username = new CloudString("Username", PersistenceType.Latest, "N");

        public static string Username
        {
            get { return s_username.Value; }
            set { s_username.Value = value; }
        }

        private static readonly CloudInt s_gold = new CloudInt("Gold", PersistenceType.Latest, 50);

        public static int Gold
        {
            get { return s_gold.Value; }
            set { s_gold.Value = value; }
        }

        private static readonly CloudString s_xP = new CloudString("XP", PersistenceType.Latest, "0,0,0,0");

        public static string XP
        {
            get { return s_xP.Value; }
            set { s_xP.Value = value; }
        }

        private static readonly CloudString s_pP = new CloudString("PP", PersistenceType.Latest, "0,0,0,0");

        public static string PP
        {
            get { return s_pP.Value; }
            set { s_pP.Value = value; }
        }

        private static readonly CloudString s_abilities = new CloudString("Abilities", PersistenceType.Latest, "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1");

        public static string Abilities
        {
            get { return s_abilities.Value; }
            set { s_abilities.Value = value; }
        }

        private static readonly CloudString s_super100 = new CloudString("Super100", PersistenceType.Latest, "1,1,1,1");

        public static string Super100
        {
            get { return s_super100.Value; }
            set { s_super100.Value = value; }
        }

        private static readonly CloudString s_super200 = new CloudString("Super200", PersistenceType.Latest, "1,1,1,1");

        public static string Super200
        {
            get { return s_super200.Value; }
            set { s_super200.Value = value; }
        }

        private static readonly CloudString s_shapeLvl = new CloudString("ShapeLvl", PersistenceType.Latest, "1,1,1,1");

        public static string ShapeLvl
        {
            get { return s_shapeLvl.Value; }
            set { s_shapeLvl.Value = value; }
        }

        private static readonly CloudString s_code = new CloudString("Code", PersistenceType.Latest, "N");

        public static string Code
        {
            get { return s_code.Value; }
            set { s_code.Value = value; }
        }

        private static readonly CloudString s_passives = new CloudString("Passives", PersistenceType.Latest, "1,1,1,0,1,1,0,0");

        public static string Passives
        {
            get { return s_passives.Value; }
            set { s_passives.Value = value; }
        }

        private static readonly CloudString s_replay = new CloudString("Replay", PersistenceType.Latest, "N");

        public static string Replay
        {
            get { return s_replay.Value; }
            set { s_replay.Value = value; }
        }

        private static readonly CloudString s_stats = new CloudString("Stats", PersistenceType.Latest, "N");

        public static string Stats
        {
            get { return s_stats.Value; }
            set { s_stats.Value = value; }
        }

        private static readonly CloudString s_super100Stats = new CloudString("Super100Stats", PersistenceType.Latest, "N");

        public static string Super100Stats
        {
            get { return s_super100Stats.Value; }
            set { s_super100Stats.Value = value; }
        }

        private static readonly CloudString s_super200Stats = new CloudString("Super200Stats", PersistenceType.Latest, "N");

        public static string Super200Stats
        {
            get { return s_super200Stats.Value; }
            set { s_super200Stats.Value = value; }
        }

        private static readonly CloudString s_levelStats = new CloudString("LevelStats", PersistenceType.Latest, "N");

        public static string LevelStats
        {
            get { return s_levelStats.Value; }
            set { s_levelStats.Value = value; }
        }

        private static readonly CloudInt s_redbolts = new CloudInt("Redbolts", PersistenceType.Latest, 0);

        public static int Redbolts
        {
            get { return s_redbolts.Value; }
            set { s_redbolts.Value = value; }
        }

        private static readonly CloudInt s_diamonds = new CloudInt("Diamonds", PersistenceType.Latest, 0);

        public static int Diamonds
        {
            get { return s_diamonds.Value; }
            set { s_diamonds.Value = value; }
        }

        private static readonly CloudString s_backgrounds = new CloudString("Backgrounds", PersistenceType.Latest, "1,0");

        public static string Backgrounds
        {
            get { return s_backgrounds.Value; }
            set { s_backgrounds.Value = value; }
        }

        private static readonly CloudString s_skins = new CloudString("Skins", PersistenceType.Latest, "1,0");

        public static string Skins
        {
            get { return s_skins.Value; }
            set { s_skins.Value = value; }
        }

        private static readonly CloudString s_emotes = new CloudString("Emotes", PersistenceType.Latest, "0,0,0");

        public static string Emotes
        {
            get { return s_emotes.Value; }
            set { s_emotes.Value = value; }
        }

        private static readonly CloudString s_maxPP = new CloudString("MaxPP", PersistenceType.Latest, "0,0,0,0");

        public static string MaxPP
        {
            get { return s_maxPP.Value; }
            set { s_maxPP.Value = value; }
        }
    }
}
